#%RAML 1.0 Library
usage:
traits:
  transcationalId: !include traits/Header trait.raml
  company Name: !include traits/queryparm company name trait.raml
  depature Location: !include traits/tdepaturelocation rait.raml
  destination location: !include traits/destinationLocation trait.raml
  TimeZone: !include traits/Time zone trait.raml